<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Visibility</name>
   <tag></tag>
   <elementGuidId>871a8b55-cb86-4661-91a2-e51e6f164b40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='visibility-row']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.accordion-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>013f9714-f6b4-4bc6-a414-9f45b0eaf941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-header</value>
      <webElementGuid>3eb9403d-0fa9-4f48-b2d3-aec2d23af05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visibility</value>
      <webElementGuid>bf6b5ce8-5f88-4569-8b76-6e8891e1a047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visibility-row&quot;)/div[@class=&quot;accordion-statement&quot;]/div[@class=&quot;accordion-header&quot;]</value>
      <webElementGuid>34ca0ca4-2c96-4175-81a6-cce627c665d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visibility-row']/div/div</value>
      <webElementGuid>c2c8b10d-58fe-4a7e-9019-9828fe509d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Achieving software quality at scale'])[1]/following::div[4]</value>
      <webElementGuid>614f4c13-4950-4df5-9b0e-2a00ddc600af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How Katalon accelerates the agile software development process'])[1]/following::div[10]</value>
      <webElementGuid>82dcd7b1-e598-484f-849e-235934e42cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scalability'])[1]/preceding::div[2]</value>
      <webElementGuid>53e0afc5-2aed-4e65-ba19-fcad61567bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div[2]/div/div/div</value>
      <webElementGuid>227f3c67-69a2-48ea-8a5d-05956670be9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Visibility' or . = 'Visibility')]</value>
      <webElementGuid>bc25a854-b9f6-4cd6-b73c-3af1dd208796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
