<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_visibility_icon</name>
   <tag></tag>
   <elementGuidId>0306f13a-318f-41bd-a052-105657d42c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.accordion-symbol</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='visibility-row']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a0b3d04f-0382-4905-93a8-7f6696b9ade4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-symbol</value>
      <webElementGuid>9248f345-580c-4c13-b8cd-db994ee75e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/visibility.svg</value>
      <webElementGuid>532b11f5-3e29-49aa-93b7-8c4b7b28fd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visibility-row&quot;)/img[@class=&quot;accordion-symbol&quot;]</value>
      <webElementGuid>c2892695-f588-4813-a14d-2e7e1b1cfd83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visibility-row']/img</value>
      <webElementGuid>5fd9ed4f-2fa5-46ed-a473-f2ce7a1216b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/visibility.svg')]</value>
      <webElementGuid>642939ae-11c4-4982-a901-5011b28c07e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>e25d79d5-9724-472f-bb1e-f3af0e637735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/visibility.svg']</value>
      <webElementGuid>5a144276-5a49-4a9f-8399-46d3d7610aed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
