<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ROI_Calculator</name>
   <tag></tag>
   <elementGuidId>4fabb55b-a422-450b-b0e9-d50abfdee5ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.redirect-ROI-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4d46ae3-50ce-4d85-9133-143870751789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>redirect-ROI-button</value>
      <webElementGuid>9b9c734f-e539-4a75-8616-fe3fd7ef7a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/test-automation-roi</value>
      <webElementGuid>468a2d9e-c3f3-4e14-ba82-60de37efef7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ROI Calculator</value>
      <webElementGuid>663933eb-397f-499f-9611-b467c1f27076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;BusinessOutcomes_wrapBusinessOutcome__StnZ3&quot;]/div[@class=&quot;redirect-row&quot;]/a[@class=&quot;redirect-ROI-button&quot;]</value>
      <webElementGuid>cc91c44f-366d-45ed-b7fc-a6af09f8ca20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/a</value>
      <webElementGuid>cc69fafb-75d9-4058-8d2b-b0dec7ef2118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ROI Calculator')]</value>
      <webElementGuid>3b28fbd7-6410-437f-aac6-ac8caf0ec218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Increased the number of user journeys through the application that could be tested'])[1]/following::a[1]</value>
      <webElementGuid>e6b739c1-90db-45b9-b129-0bfdab319cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success Stories'])[2]/preceding::a[1]</value>
      <webElementGuid>9003784b-de07-4627-9cd1-7bcf73f40372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Katalon'])[4]/preceding::a[2]</value>
      <webElementGuid>1f3797e5-4cc6-4257-b53e-834a14346c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ROI Calculator']/parent::*</value>
      <webElementGuid>539f4aeb-f3be-473e-bfa0-7750fff115a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/test-automation-roi')]</value>
      <webElementGuid>533db030-b94e-4984-9ca7-75f8049faf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>89c520f2-ced2-4bca-bf61-fe0fb8d4c5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/test-automation-roi' and (text() = 'ROI Calculator' or . = 'ROI Calculator')]</value>
      <webElementGuid>d778f8d3-39de-4a73-a70f-bf187899e6d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
