<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Visibility_accordion-arrow</name>
   <tag></tag>
   <elementGuidId>86eced4f-5cd4-479a-a8bc-b912e951f2c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='visibility-row']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.accordion-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2b2a6d40-2a89-4d36-95ed-88081cf9dedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-arrow</value>
      <webElementGuid>c064340a-eaa1-43b5-b9db-ce150a53665a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/Plus.svg</value>
      <webElementGuid>7e8af7b5-68d4-4717-a2e0-8363eced42ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visibility-row&quot;)/div[@class=&quot;accordion-statement&quot;]/div[@class=&quot;accordion-header&quot;]/img[@class=&quot;accordion-arrow&quot;]</value>
      <webElementGuid>8c355bfc-fe89-4a8f-9543-9d891444c975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visibility-row']/div/div/img</value>
      <webElementGuid>33061d59-52bb-4328-a826-119d57aee5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/Plus.svg')]</value>
      <webElementGuid>9b16d22f-cd11-49c4-b642-03acef492ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>6681b947-bbe1-4d6b-9e0d-71583e316891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/Plus.svg']</value>
      <webElementGuid>70b8a008-8515-4230-9114-5c9b27e82da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
