<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Business_Outcomes_footer</name>
   <tag></tag>
   <elementGuidId>210f9383-6251-4bbf-a49f-7e77f4239f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[3]/footer/div/div[2]/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link.why-katalon-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d79abff-7be3-44c6-a633-47ee18823356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link why-katalon-link</value>
      <webElementGuid>1455283f-b63a-4b96-8d2b-779cb6698edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/business-outcomes</value>
      <webElementGuid>3174c21b-3763-416c-9287-833332fdbd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business Outcomes</value>
      <webElementGuid>1fc74ce0-37b2-4f46-b83e-d7965725d861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Footer_wrapFooter__2HFBG&quot;]/footer[@class=&quot;katalon-footer&quot;]/div[@class=&quot;footer-wrapper&quot;]/div[@class=&quot;footer-right&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;footer-section why-katalon&quot;]/div[@class=&quot;list why-katalon-list&quot;]/a[@class=&quot;link why-katalon-link&quot;]</value>
      <webElementGuid>1eebed67-613a-4070-bfe8-871b0069f3da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/footer/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>1ec0e9e0-2c07-45fb-a4f9-f5cbaadbec49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Business Outcomes')])[2]</value>
      <webElementGuid>bcd2df32-bbd1-48a1-a20e-dc487a84ce5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Katalon'])[4]/following::a[1]</value>
      <webElementGuid>74c07aed-9bfa-4fad-abd9-936e7addf5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Katalon Technology Partner'])[1]/following::a[1]</value>
      <webElementGuid>22a8c81e-4511-4be4-af2d-eaf3ead96efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Speed'])[1]/preceding::a[1]</value>
      <webElementGuid>90e08232-4136-4c1d-b8a9-15185c2905f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flexibility &amp; Scalability'])[1]/preceding::a[2]</value>
      <webElementGuid>4394996c-1008-4db7-81a2-650703a2b0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/business-outcomes')])[15]</value>
      <webElementGuid>621e305a-2c62-4933-9bf5-167fdc841b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>0b8266ff-970c-4bd0-a544-6b7e37072661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/business-outcomes' and (text() = 'Business Outcomes' or . = 'Business Outcomes')]</value>
      <webElementGuid>cb4951ff-76c5-42a2-ade3-d21159f3af36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
