<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_complexity_level</name>
   <tag></tag>
   <elementGuidId>a46af42b-5dbe-400d-9514-46072649ad68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#complexity-report</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='complexity-report']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>736510c4-a2d0-48a8-a45a-e77265fc1b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>743dfe8c-6371-4a01-9754-bd5be25f4ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>complexity-report</value>
      <webElementGuid>a2d6d64b-a996-4196-adc0-6436a95eaa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>complexity-report</value>
      <webElementGuid>efc44b16-d227-4e27-b648-ad5b1914bacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medium</value>
      <webElementGuid>9d445f3e-126c-48f3-bc10-25600e8c2bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complexity-report&quot;)</value>
      <webElementGuid>64779086-7c3f-4adf-9933-6e9f1aef1be8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='complexity-report']</value>
      <webElementGuid>cdfe853d-1788-43e7-bdc4-ef132e3bcf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>26cd9f5e-65dc-4573-8a30-7560479a3fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hard'])[1]/following::div[1]</value>
      <webElementGuid>92bb89e8-8eb2-4050-98f7-c841b95fb82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/following::div[2]</value>
      <webElementGuid>80a175b9-727d-4887-9340-cec69f2a2eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use our auto-filled inputs?'])[2]/preceding::div[2]</value>
      <webElementGuid>4e738c1c-1fff-4d63-8d8c-3870abad08a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We help you fill in the rest of the inputs based on your previous answer.'])[2]/preceding::div[3]</value>
      <webElementGuid>dce62426-6968-41ab-b64f-51bb9419c25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>d0ef00fc-3841-4743-af52-27946104bbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'complexity-report' and (text() = 'Medium' or . = 'Medium')]</value>
      <webElementGuid>edf9953b-180d-4073-8fbc-c8dcf14455ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
