<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_count</name>
   <tag></tag>
   <elementGuidId>2c955082-64c9-4910-891c-ca4a826edaff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Q4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Q4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17fc286b-74c9-4fd0-9a9d-087774de2845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>611a0325-4d74-447b-a3df-dda0dad14f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Q4</value>
      <webElementGuid>63f959aa-f3b6-4fc0-8ce1-1c797349e59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bbbb5a4c-fba7-48b7-9898-dee8e105e9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Q4&quot;)</value>
      <webElementGuid>5727cb51-b0e2-455d-b2b6-2c851274dc69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Q4']</value>
      <webElementGuid>54ec150b-8a87-4a70-b2ce-ab3086b8e90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>474e16fe-2311-4853-8253-00b52e47fe97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>c5998a16-c0ef-47f6-9ce2-fb6ef49915fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Q4' and @placeholder = '10']</value>
      <webElementGuid>5082dc7a-dc12-4e7a-8803-48cd17b85700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
