<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_product</name>
   <tag></tag>
   <elementGuidId>00eafc2c-8fc0-412f-91d9-f6e706e69967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Q2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Q2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0f8117c-5bd4-4969-b90b-3ee218a13dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee0d8ecc-8492-446b-a977-11a19efb9536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Q2</value>
      <webElementGuid>4fe363f8-7067-4227-a0eb-16f75db65309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a1c1045f-08b3-4643-8063-48be1f7d0a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Q2&quot;)</value>
      <webElementGuid>9003e83f-8d1a-4ef5-8c14-2f674a41485a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Q2']</value>
      <webElementGuid>2e2ab530-e79a-46c3-befd-56477f9242dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>76a9b3f8-245b-465a-ac2f-7567e153ae1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>03f60563-48c8-4c59-a27b-a736f295f5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Q2' and @placeholder = '3']</value>
      <webElementGuid>b3186554-a43d-485b-83d4-4b15bb5fdc7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
