<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_team_size</name>
   <tag></tag>
   <elementGuidId>bd7543bb-d016-411d-a3b2-cc7cb1eae208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company-size-report</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='company-size-report']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37ea7b94-0c77-4d73-9f91-7b7cd8deef43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>e15641b6-4452-43aa-98f4-a4d2c25b4b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>03eb4289-b560-4406-a651-3e482dbea117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>6bfb6b4b-7ba4-4ddf-a705-b34c6226444c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Small (1-2 testers and 3-6 software engineers)</value>
      <webElementGuid>f42fd993-e3ee-4334-ba34-0531cc3869bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company-size-report&quot;)</value>
      <webElementGuid>7ad60a59-f292-4fcf-a818-33e0c5fadb41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='company-size-report']</value>
      <webElementGuid>6e98a70f-a6da-47c2-9a73-ba647ee63229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>713fbc75-f50e-404c-949b-7bdce5fbd7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Large (5-6 testers and 12-15 software engineers)'])[1]/following::div[1]</value>
      <webElementGuid>e091bae8-87f2-455b-b6d4-6267d750c57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium (3-4 testers and 7-10 software engineers)'])[1]/following::div[2]</value>
      <webElementGuid>07564956-5897-4173-bba5-a0c6c33a93b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How many products do you typically test?'])[1]/preceding::div[1]</value>
      <webElementGuid>b746ad26-f5c0-4923-a78e-5f3dfca7b7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use our auto-filled inputs?'])[1]/preceding::div[3]</value>
      <webElementGuid>e27d7cdd-6c68-4b17-b66e-13af8ad4529c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>ed1ae51e-ae82-4fe4-81c5-0a5c3816bf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'company-size-report' and (text() = 'Small (1-2 testers and 3-6 software engineers)' or . = 'Small (1-2 testers and 3-6 software engineers)')]</value>
      <webElementGuid>c3e91f60-e518-49ca-b1a6-4bc07c1fbb94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
