<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>team_option_1</name>
   <tag></tag>
   <elementGuidId>4203318e-daa0-4123-9c29-41a8dde5806b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf6ac82f-76f1-43ef-8814-35c3a94d27d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9e3b302a-b6e6-45ba-a9ae-42110e33f310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>19dcd816-39bc-4453-bae4-f95c3e5b583f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>6486ed46-4b5c-4cfd-aea7-59a7c23143ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Small (1-2 testers and 3-6 software engineers)</value>
      <webElementGuid>b609f7e2-bcc5-4838-b3cb-28e5c3f43909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;TestAutomationROI_wrapTestAutomationROI__SmMA1&quot;]/div[@class=&quot;roi-content-container&quot;]/div[@class=&quot;calculate-result-section&quot;]/div[@class=&quot;calculate-section&quot;]/div[@class=&quot;calculate-form&quot;]/div[@class=&quot;calculate-question first-ques&quot;]/div[@class=&quot;select-input-company-size active&quot;]/div[@class=&quot;select-box company-size&quot;]/div[@class=&quot;options-container company-size-report active&quot;]/div[@class=&quot;option&quot;]</value>
      <webElementGuid>b0ea159a-1f5b-425f-b309-34961e798a83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>a0b50554-a9d1-4747-8808-a2678c1d16d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team size'])[1]/following::div[4]</value>
      <webElementGuid>485e4c8c-36a0-490f-8ba6-0479a041e7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use the calculator below'])[1]/following::div[7]</value>
      <webElementGuid>92b5c2b5-1e76-43fd-914a-aa3fae18c9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium (3-4 testers and 7-10 software engineers)'])[1]/preceding::div[1]</value>
      <webElementGuid>1f4f36c4-20f1-4fc0-a256-1b5a2a815f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>11c2c4a1-a324-49c5-b5b5-bbd3f901355c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Small (1-2 testers and 3-6 software engineers)' or . = 'Small (1-2 testers and 3-6 software engineers)')]</value>
      <webElementGuid>5d7f4841-2ff2-4aee-a807-2272b4f39e01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
