<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Low_complexity</name>
   <tag></tag>
   <elementGuidId>e5b2fa6f-3f36-42bb-91f4-bdcae7a8ea4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.options-container.complexity-report.active > div.option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[3]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85c5fd42-ad42-437e-a9cb-ad75f18b5313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9e4b9b21-3b28-40ac-afb9-537b5992419e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>complexity-report</value>
      <webElementGuid>8aa34c71-cb9e-49ee-b8a0-8cb4356c0291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>low-complex</value>
      <webElementGuid>518991a1-24ec-424b-8993-3cad52c18b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Low</value>
      <webElementGuid>6b129880-325b-4d7d-9c74-c6a9ab61b68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;TestAutomationROI_wrapTestAutomationROI__SmMA1&quot;]/div[@class=&quot;roi-content-container&quot;]/div[@class=&quot;calculate-result-section&quot;]/div[@class=&quot;calculate-section&quot;]/div[@class=&quot;calculate-form&quot;]/div[@class=&quot;calculate-question&quot;]/div[@class=&quot;select-input-complexity active&quot;]/div[@class=&quot;select-box complexity&quot;]/div[@class=&quot;options-container complexity-report active&quot;]/div[@class=&quot;option&quot;]</value>
      <webElementGuid>12f993ed-f741-4bcd-9fec-ea97978c765b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[3]/div[2]/div/div/div</value>
      <webElementGuid>2e28f765-5269-41aa-b86b-8ef7836a7c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test case complexity level'])[1]/following::div[4]</value>
      <webElementGuid>bd1e0b7a-afaa-4a88-866c-eacfac04e780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We help you fill in the rest of the inputs based on your previous answer.'])[1]/following::div[6]</value>
      <webElementGuid>a43be15d-22a8-4f7b-9baf-0f7eef580023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/preceding::div[1]</value>
      <webElementGuid>07f7c85b-a050-48d5-b444-24d6fa307815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div/div</value>
      <webElementGuid>409c7aa5-dd91-4dc7-9e3d-c55a4ec48627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Low' or . = 'Low')]</value>
      <webElementGuid>a15574f3-1468-47b0-9524-726d85cb34c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
