<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Calculate</name>
   <tag></tag>
   <elementGuidId>1f4055ab-eb2d-45a7-bcaf-ed70de12615d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.calculate-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f212e2d2-52b2-40ac-8713-fbba4d156bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calculate-submit</value>
      <webElementGuid>da77955a-d7b0-4818-afe2-c637e8cb9a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>5de137fe-ca0a-4937-89a5-9aaa341815ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;TestAutomationROI_wrapTestAutomationROI__SmMA1&quot;]/div[@class=&quot;roi-content-container&quot;]/div[@class=&quot;calculate-result-section&quot;]/div[@class=&quot;calculate-section&quot;]/div[@class=&quot;calculate-form&quot;]/div[@class=&quot;calculate-submit&quot;]</value>
      <webElementGuid>7e08cd03-b27a-44d8-a242-4c38bd2ccc53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[6]</value>
      <webElementGuid>c27f34d9-c710-4e35-900f-35b5d1f571fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill in all required field(s)'])[1]/following::div[1]</value>
      <webElementGuid>f1b4ec21-97f4-4c58-bcb7-3daa4e20003c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We help you fill in the rest of the inputs based on your previous answer.'])[3]/following::div[2]</value>
      <webElementGuid>93726e8e-7538-48a1-a791-772e14a60502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How you save with the Katalon Platform'])[1]/preceding::div[2]</value>
      <webElementGuid>b6ab02fe-5738-46e8-9bec-0f6fba787419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[6]</value>
      <webElementGuid>3392e427-605d-496e-9712-d6623616736d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Calculate' or . = 'Calculate')]</value>
      <webElementGuid>b996533f-de2a-478e-a6ae-bd760e84ac12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
