<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_complexity_level</name>
   <tag></tag>
   <elementGuidId>3311f7e4-a6a6-4db8-9c41-0e0d7002dd4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#complexity-report</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='complexity-report']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c725b542-cbab-444d-8f4d-fbaa920c0510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>4317135b-6dad-47b2-a742-8b918c67294c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>complexity-report</value>
      <webElementGuid>1145a759-9249-4886-b1b5-e2209b9e034c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>complexity-report</value>
      <webElementGuid>be6ce0b9-d12a-40c5-8fa9-0656b0ca5e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medium</value>
      <webElementGuid>2cde1df0-fced-47c2-a2cf-4929f31edd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complexity-report&quot;)</value>
      <webElementGuid>6e14bf0c-d6b7-4629-9665-6620ea371d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='complexity-report']</value>
      <webElementGuid>d2d400a4-e2b1-4064-ae79-739e0cbb19d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>a93addcb-90fb-4c63-b1a6-3c1c21476e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hard'])[1]/following::div[1]</value>
      <webElementGuid>4ab1636f-7f16-4eaa-aa53-87c98f436c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/following::div[2]</value>
      <webElementGuid>1d5bb55c-19b4-4619-8b80-764501e5d1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use our auto-filled inputs?'])[2]/preceding::div[2]</value>
      <webElementGuid>b7eeab2b-f712-4d33-94ef-232c944c39e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We help you fill in the rest of the inputs based on your previous answer.'])[2]/preceding::div[3]</value>
      <webElementGuid>de28c003-19d2-4a4e-91e8-c8ca93af1c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>dbcf141e-17a3-4610-b06b-7af4493fb2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'complexity-report' and (text() = 'Medium' or . = 'Medium')]</value>
      <webElementGuid>be92fa18-38a5-490e-841e-1c58b0276d0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
