<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_product</name>
   <tag></tag>
   <elementGuidId>24bec488-dabe-45d9-b3c0-f369c154e3a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Q2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Q2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12590dc8-ed44-42c7-ad2d-a79906e3dca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c30aa39a-e06e-4efd-b582-d045d6a28771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Q2</value>
      <webElementGuid>4fb41e96-7094-4d8a-b0f1-43899239cd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e735e33c-2af2-4c82-b689-b3563cf13a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Q2&quot;)</value>
      <webElementGuid>d6c79647-c5a7-43db-9774-89688590ab99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Q2']</value>
      <webElementGuid>b92394d9-1389-4961-b41e-0d3346cfff5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>d1c4ae82-9d20-4170-a029-d5fe305ab00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>412507b7-c164-405c-8d2b-0b0de010d172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Q2' and @placeholder = '3']</value>
      <webElementGuid>27268ab1-55b0-40a8-9dbf-298d865d265e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
