<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_count</name>
   <tag></tag>
   <elementGuidId>bb4ae2bd-04aa-499b-ae40-c8604e85cec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Q4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Q4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72c46162-a608-4e85-bb38-5c6ae02b230b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d00f4f72-3528-4bdb-ab13-c0ae7cbe51a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Q4</value>
      <webElementGuid>5ec2a1d9-49eb-4f7d-99b0-f4d8d1c43269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>afac8762-3f59-4501-85a1-a7d0eb8212ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Q4&quot;)</value>
      <webElementGuid>bb775e27-5c66-4853-bfcf-ed703419971f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Q4']</value>
      <webElementGuid>cb6eadbe-cfad-4acd-a9bf-283aa8cde512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>a7a434f4-b11c-4a39-9a15-7f7b0db00fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>b684d40c-f5fc-4f47-b7ec-57828c8d6a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Q4' and @placeholder = '10']</value>
      <webElementGuid>6d785626-871e-4a65-8550-52fbc512adbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
