<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>medium_team</name>
   <tag></tag>
   <elementGuidId>f7752014-d579-4266-a7a8-dc236275d84c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7cb0dd0d-729d-4676-8018-4d12150d1bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5c3c00ec-24cc-495c-80b4-cc05bb545624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>92f19e2d-bf12-4204-a17b-f5c4e71f295c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>med</value>
      <webElementGuid>921f992a-8e2b-4c5b-b23a-79b2bdba5903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medium (3-4 testers and 7-10 software engineers)</value>
      <webElementGuid>a5f21327-f91f-4cc4-875f-453db2f4c2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;TestAutomationROI_wrapTestAutomationROI__SmMA1&quot;]/div[@class=&quot;roi-content-container&quot;]/div[@class=&quot;calculate-result-section&quot;]/div[@class=&quot;calculate-section&quot;]/div[@class=&quot;calculate-form&quot;]/div[@class=&quot;calculate-question first-ques&quot;]/div[@class=&quot;select-input-company-size active&quot;]/div[@class=&quot;select-box company-size&quot;]/div[@class=&quot;options-container company-size-report active&quot;]/div[@class=&quot;option&quot;]</value>
      <webElementGuid>d2d477d5-df41-4c15-bef5-140864021963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>66a63633-55af-4ee5-adbd-93c35209ecfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Small (1-2 testers and 3-6 software engineers)'])[1]/following::div[1]</value>
      <webElementGuid>fbf11a33-5fde-4345-b35c-317f9d1a0a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team size'])[1]/following::div[5]</value>
      <webElementGuid>772453bc-6c6a-4e94-a49b-6fe4e5a62821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Large (5-6 testers and 12-15 software engineers)'])[1]/preceding::div[1]</value>
      <webElementGuid>001ea725-a365-44ad-81d1-5670ac21b0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>69fecdc9-6217-4533-b996-7dd9c5f2f14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Medium (3-4 testers and 7-10 software engineers)' or . = 'Medium (3-4 testers and 7-10 software engineers)')]</value>
      <webElementGuid>6c1ca8e2-3a05-40c6-bb07-5652cbd9a923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
