<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_team_size</name>
   <tag></tag>
   <elementGuidId>03e1e574-c387-46d2-9373-7462252b86f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company-size-report</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='company-size-report']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19f69528-4f51-4d73-abc0-5c4162039f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>6b7bb8c3-be7c-459c-8b1b-e3a4f79e724c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>a0c4fecd-6ee6-43b2-9c88-07fd2e1d6ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>89c704e8-6955-496a-baff-a05edd56d8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Small (1-2 testers and 3-6 software engineers)</value>
      <webElementGuid>dd9af45d-4430-4c6e-b504-2d4938ce0d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company-size-report&quot;)</value>
      <webElementGuid>b86eb83a-95ba-4315-a4e8-e612d1f865ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='company-size-report']</value>
      <webElementGuid>8190d9f2-2605-4098-af1a-68170ed8db6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>87c0e8a9-e989-47fc-86cf-83b3fbe57c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Large (5-6 testers and 12-15 software engineers)'])[1]/following::div[1]</value>
      <webElementGuid>84aee543-60dc-4009-92dc-8372c7891e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium (3-4 testers and 7-10 software engineers)'])[1]/following::div[2]</value>
      <webElementGuid>02ebdd1d-f806-4ebd-800d-dc0ec1fd975c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How many products do you typically test?'])[1]/preceding::div[1]</value>
      <webElementGuid>f20959d0-5856-430d-af25-3634c764c745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use our auto-filled inputs?'])[1]/preceding::div[3]</value>
      <webElementGuid>d0056ebb-096f-451d-bdb0-1ba402c13e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>f656044f-b7e2-4e8b-9de6-906cb643ec50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'company-size-report' and (text() = 'Small (1-2 testers and 3-6 software engineers)' or . = 'Small (1-2 testers and 3-6 software engineers)')]</value>
      <webElementGuid>bb23f257-ad49-404a-a278-83f03a979ca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
