<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>team_option_1</name>
   <tag></tag>
   <elementGuidId>a02d3833-cb65-44e8-bc74-5c5fb3c31e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>23e735ca-8f12-4049-93a6-fee1c0bb9c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9f02ff59-4d5f-40ad-bc99-3dacded91fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>d6eaffc5-e14a-4ba3-b349-8ba40bcd20b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>49bd18b8-9e57-4455-aa0c-e06bf4314ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Small (1-2 testers and 3-6 software engineers)</value>
      <webElementGuid>29d91d84-7e53-4d6d-a178-fa33d329a519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;TestAutomationROI_wrapTestAutomationROI__SmMA1&quot;]/div[@class=&quot;roi-content-container&quot;]/div[@class=&quot;calculate-result-section&quot;]/div[@class=&quot;calculate-section&quot;]/div[@class=&quot;calculate-form&quot;]/div[@class=&quot;calculate-question first-ques&quot;]/div[@class=&quot;select-input-company-size active&quot;]/div[@class=&quot;select-box company-size&quot;]/div[@class=&quot;options-container company-size-report active&quot;]/div[@class=&quot;option&quot;]</value>
      <webElementGuid>97ee7e57-4e7a-4495-8f39-de6d209af8d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>fb64c54b-bf67-4c70-bda4-c5b43f0fcd63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team size'])[1]/following::div[4]</value>
      <webElementGuid>7641bdc4-5c8b-41f9-b00c-ad7cb6d32102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use the calculator below'])[1]/following::div[7]</value>
      <webElementGuid>fa673e83-dc1d-4978-8cda-8fe7337f6665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium (3-4 testers and 7-10 software engineers)'])[1]/preceding::div[1]</value>
      <webElementGuid>36c1fb12-7817-4461-9619-c7adc12f9a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>d8cfcbcc-a941-4b78-addf-4ddc3ad9836b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Small (1-2 testers and 3-6 software engineers)' or . = 'Small (1-2 testers and 3-6 software engineers)')]</value>
      <webElementGuid>a3f0c16a-769d-47c7-8038-9528950046a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
