<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>team_option</name>
   <tag></tag>
   <elementGuidId>64f53f4f-c7a0-463a-b8b5-3f12f45bf4cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='company-size-report']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#company-size-report</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9086c5c8-3f2b-4c73-a19c-6a6efcf0cd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>d70de129-bbaa-4514-a9ef-3f1cc00d42ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>80e07c20-6f11-4e1a-bf2c-bd9e1175790a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select</name>
      <type>Main</type>
      <value>company-size-report</value>
      <webElementGuid>eb3229a7-75a6-4b10-898e-94f174b2a9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Small (1-2 testers and 3-6 software engineers)</value>
      <webElementGuid>b64149f2-2551-40ae-ab0e-cefb0ec7e6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company-size-report&quot;)</value>
      <webElementGuid>11551766-2771-432b-8f72-aef1c15ca7d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='company-size-report']</value>
      <webElementGuid>9ec219e1-1b3a-40c3-83be-6a7586c6c352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>018b32fb-1181-4a98-a883-ed3d39839245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Large (5-6 testers and 12-15 software engineers)'])[1]/following::div[1]</value>
      <webElementGuid>1ba885cc-25bc-46e5-9331-a9efcd630296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium (3-4 testers and 7-10 software engineers)'])[1]/following::div[2]</value>
      <webElementGuid>9fc582ba-9542-45b4-b4de-c2b60d8d4fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How many products do you typically test?'])[1]/preceding::div[1]</value>
      <webElementGuid>c8bf39d4-5573-4623-9478-d7ec1ec7ed5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use our auto-filled inputs?'])[1]/preceding::div[3]</value>
      <webElementGuid>514c9779-d450-4e06-93dd-3b9b2f40eda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>191547f7-0403-4ba5-9052-b8a23b7710e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'company-size-report' and (text() = 'Small (1-2 testers and 3-6 software engineers)' or . = 'Small (1-2 testers and 3-6 software engineers)')]</value>
      <webElementGuid>85ef58f4-1247-40e3-bf18-c5c9ff9bcd49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
